### Signup with username and password
POST http://localhost:5000/api/users
Content-Type: application/json

{
    "username":"singh@gmail.com",
    "password":"sharad123"
}

###  Login with username and password
POST http://localhost:5000/api/users/login
Content-Type: application/json

{
    "username":"singh@gmail.com",
    "password":"sharad123"
}


### Only a Authenticated user can get and create a product
### Get all products
GET http://localhost:5000/api/products/
Content-Type: application/json
Authorization: Bearer <Token>

### Get all products by category
### You can try with two categories: smartphones and laptops
GET http://localhost:5000/api/products/search?category=smartphones
Content-Type: application/json
Authorization: Bearer <Token>


### Create a product
POST http://localhost:5000/api/products/create
Content-Type: application/json
Authorization: Bearer <Token> 

{
    "title": "HP Pavilion 15-DK1056WM",
    "description": "HP Pavilion 15-DK1056WM Gaming Laptop 10th Gen Core i5, 8GB, 256GB SSD, GTX 1650 4GB, Windows 10",
    "price": 1099,
    "discountPercentage": 6.18,
    "rating": 4.43,
    "stock": 89,
    "brand": "HP Pavilion",
    "category": "laptops",
    "thumbnail": "https://i.dummyjson.com/data/products/10/thumbnail.jpeg"
    
}
